name: Tests
on:
  push:
    branches: [master]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ['3.9', '3.10', '3.11']
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install -r requirements_dev.txt
      - name: Run tests
        run: pytest
